staging/src/k8s.io/kube-aggregator/hack/update-codegen.sh

Needed to generate code for the aggregation beta types.

UPSTREAM: <drop>: shell script for beta

---

pkg/features/kube_features.go
pkg/kubelet/kubelet_node_status_test.go

UPSTREAM: <carry>: disable local storage isolation feature gate

---

hack/generate-bindata.sh

UPSTREAM: <carry>: Enable nested generation of k8s.io/kubernetes bindata

---

openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go

https://github.com/openshift/kubernetes/pull/208 got lost during rebase.

Reapply: UPSTREAM: <carry>: oauth-authn: support sha256 prefixed tokens

---

pkg/kubelet/pleg/generic.go
pkg/kubelet/pleg/generic_test.go

xref https://github.com/kubernetes/kubernetes/pull/85983
xref https://bugzilla.redhat.com/show_bug.cgi?id=1861631

Bug 1861631: UPSTREAM: 85983: fix metrics kubelet_running_pod_count

---

openshift-kube-apiserver/authentication/oauth/bootstrapauthenticator.go
openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go

Implementing https://github.com/openshift/enhancements/pull/420.

oauth-token-authn: switch to sha256~ prefix

---

staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go

Upstream cherry-pick: https://github.com/kubernetes/kubernetes/pull/93971

BUG 1863009: vSphere provision failure on ocp46

---

cmd/watch-termination/main.go

- the loop creating the event was racing with the code touching the new .terminating file
- the event message lacked the hostname
- the termination.log file lacked the warning about the non-graceful termination which made it hard to follow.

Bug 1875841: watch-termination: fix deletion race and write non-graceful message also to termination.log

---

pkg/controller/endpoint/endpoints_controller.go
pkg/controller/endpoint/endpoints_controller_test.go
pkg/registry/core/endpoint/BUILD
pkg/registry/core/endpoint/strategy.go
test/integration/BUILD
test/integration/endpoints/BUILD
test/integration/endpoints/endpoints_test.go
test/integration/endpoints/main_test.go

…re comparing
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
Fixes #
```release-note
```
```docs
```

Bug 1854434: UPSTREAM: 94112: Remove canonicalization of endpoints by endpoints controller for better comparison

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go
test/e2e/apps/statefulset.go
test/e2e/examples.go
test/e2e/framework/ingress/ingress_utils.go
test/e2e/framework/kubectl/kubectl_utils.go
test/e2e/framework/util.go
test/e2e/kubectl/kubectl.go
test/e2e/storage/testsuites/subpath.go
test/e2e/storage/vsphere/vsphere_utils.go
test/e2e/upgrades/cassandra.go
test/e2e/upgrades/etcd.go
test/e2e/upgrades/mysql.go

/assign @marun 
I wasn't sure if you want to have a separate commit to remove 5bb5b37d2cb43baa14b59485ad306490f75719fd if so, lemme know.

Bug 1875194: UPSTREAM: 94609: Use namespace flag passed to RunKubectl* methods

---

openshift-hack/test-kubernetes-e2e.sh

Using the 1.19.x catchall bz to reflect the importance of this PR to future rebasing efforts.

Bug 1873043: Enable k8s-e2e-gcp-serial

---

test/e2e/storage/testsuites/snapshottable.go

Fixes a flake https://bugzilla.redhat.com/show_bug.cgi?id=1877338
ref https://github.com/kubernetes/kubernetes/pull/94653

Bug 1877338: UPSTREAM: 94653: Tolerate NotFound errors when deleting snapshots

---

staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go

/kind bug
Currently `Count` includes keys from different resource(s): any key (belonging to a different resource) that has the specified key as a prefix will be included in the count.
Consider the following keys:
```
A: <storage-prefix>//foo.bar.io/machines
B: <storage-prefix>//foo.bar.io/machinesets
```
If we ask for the count of key A, the result will also include the keys from key B since key B shares the same prefix as key A.
Append a separator to mark the end of the key, this will exclude all other keys from a different resource that is a prefix of the specified key.
* I am wondering if this change has any ripple effects. Is there any code site that relies on the current behavior …

Bug 1866814: UPSTREAM: 94773: count of etcd object should be limited to the specified resource

---

cmd/watch-termination/main.go

We saw a case https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-4.6/1308308963082637312 where kube-apiserver does not terminate.
This PR removes the termination lock file in that case and creates a GracefulTerminationTimeout event right away.

Bug 1882750: UPSTREAM: <carry>: watch-termination: avoid false positives of NonGracefulTermination events

---

test/e2e/node/pods.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1884697
https://github.com/kubernetes/kubernetes/pull/95261
@deads2k

Bug 1884697: UPSTREAM: 95261: test: e2e: fix race in pods test

---

pkg/volume/rbd/rbd_util.go

Fix https://bugzilla.redhat.com/show_bug.cgi?id=1887292
https://github.com/kubernetes/kubernetes/pull/95245

Bug 1887292: UPSTREAM: 95245: Mask Ceph RBD adminSecrets in logs when logLevel >= 4

---

cmd/controller-manager/app/serve.go
cmd/kube-scheduler/app/server.go
pkg/kubeapiserver/server/insecure_handler.go
staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
staging/src/k8s.io/apiserver/pkg/server/config.go
staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go

UPSTREAM 95002: no stack on panic timeout

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/types.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/sort/bypriority.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/sort/byrestrictions.go
vendor/modules.txt

Bumping to get https://github.com/openshift/apiserver-library-go/pull/38.

scc-admission: add audit annotations with reason

---

pkg/controller/podautoscaler/replica_calculator.go
pkg/controller/podautoscaler/replica_calculator_test.go

xref https://github.com/kubernetes/kubernetes/pull/95560

Bug 1897754: HPA: Ignore deleted pods.

---

pkg/volume/vsphere_volume/vsphere_volume_util.go

Reduce volume name length for vsphere.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1884800

Bug 1884800: Reduce volume name length for vsphere

---

pkg/proxy/iptables/proxier.go
pkg/proxy/iptables/proxier_test.go

backport of #442 to pick upstream commit
this will be rebased into sdn branch 4.6

UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain

---

REBASE.openshift.md

- Add new section 'Maintaining this document'
- Move checklist above the instructions to emphasize their importance
- Add new section 'Reacting to new commits'
- Mention that generated changes in carries should be dropped

UPSTREAM: <carry>: (squash) Add detail to rebase doc

---

staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go

What type of PR is this?
/kind bug
What this PR does / why we need it:
This is a refactoring to tiptoe around golang/go#43570 for #97685
Which issue(s) this PR fixes:
Fixes #97685
Special notes for your reviewer:
This is an alternative to #97791 and #97854
Does this PR introduce a user-facing change?:
Performance regresssion #97685 has been fixed.
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

Bug 1915582: UPSTREAM: 97860: move all variables in sampleAndWaterMarkHistograms::innerSet

---

staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go

What type of PR is this?
/kind bug
What this PR does / why we need it:
- Changed quantization to use monotonic clock readings, because wall clock time can go backwards.
Stopping panicing when monotonic clock readings go backwards, because #96459 reported it happening.
Also re-organized a func to use defer ...Unlock() instead of an Unlock() call in the midst of straight-line code, because the former is the preferred pattern.
- This is a refactoring to tiptoe around golang/go#43570 for #97685
Which issue(s) this PR fixes:
- Fixes #96459
- Fixes #97685
Special notes for your reviewer:
This is an alternative to #97791 and #97854
Does this PR introduce a user-facing change?:
Performance regresssion #97685 has been fixed.

Bug 1915583: UPSTREAM: 97860: move all variables in sampleAndWaterMarkHistograms::innerSet

---

test/e2e/scheduling/predicates.go
test/e2e/scheduling/priorities.go

Backporting https://github.com/kubernetes/kubernetes/pull/94684

bug 1870342: UPSTREAM: 94684: e2e: Pod should avoid nodes that have avoidPod annotation: clean remaining pods

---

pkg/kubelet/cm/BUILD
pkg/kubelet/cm/container_manager_linux.go
pkg/kubelet/cm/cpumanager/cpu_manager.go
pkg/kubelet/cm/cpumanager/cpu_manager_test.go
pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
pkg/kubelet/cm/cpuset/cpuset.go
pkg/kubelet/cm/fake_internal_container_lifecycle.go
pkg/kubelet/cm/internal_container_lifecycle.go
pkg/kubelet/cm/internal_container_lifecycle_linux.go
pkg/kubelet/cm/internal_container_lifecycle_unsupported.go
pkg/kubelet/cm/internal_container_lifecycle_windows.go
pkg/kubelet/dockershim/helpers_linux.go
pkg/kubelet/kuberuntime/kuberuntime_container.go

Upstream PR: kubernetes#98019
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1920368
/cc @rphillips

Bug 1920368: UPSTREAM: 98019: specify the container CPU set during the creation

---

pkg/kubelet/kuberuntime/kuberuntime_manager.go
pkg/kubelet/kuberuntime/kuberuntime_manager_test.go

Ignore not found errors within status messages.

Bug 1926285: UPSTREAM: <carry>: ignore not found errors in status messages

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
test/e2e/apimachinery/BUILD
test/e2e/apimachinery/flowcontrol.go

Pick both:
- https://github.com/kubernetes/kubernetes/pull/96984 
- https://github.com/kubernetes/kubernetes/pull/96966 
Which issue(s) this PR fixes:
Related to #96803 and #96893

Bug 1929012: UPSTREAM: 96984: APF e2e: wait for steady state before proceeding

---

pkg/kubelet/kubelet_pods.go
pkg/kubelet/kubelet_test.go

Merged upstream Ref: https://github.com/kubernetes/kubernetes/pull/98956

UPSTREAM: 98956: Fix race when KillPod followed by IsPodPendingTermining

---

pkg/kubelet/kuberuntime/fake_kuberuntime_manager.go
pkg/kubelet/kuberuntime/kuberuntime_manager.go
pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
staging/src/k8s.io/cri-api/pkg/apis/testing/fake_runtime_service.go

Upstream Ref: https://github.com/kubernetes/kubernetes/pull/98933

Bug 1908378: kubelet: fix create sandbox delete pod race

---

pkg/kubelet/cm/container_manager_linux.go
pkg/kubelet/nodestatus/setters.go

Fixes a periodic log. Upstream Ref: https://github.com/kubernetes/kubernetes/pull/96958

Bug 1931103: UPSTREAM: 96958: kubelet: remove periodic messages from log-level 2

---

staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go

fixes a test that @p0lyn0mial asked about

UPSTREAM: 99199: delay serving CRD creates for a few seconds for HA consistency

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
test/e2e/apimachinery/BUILD
test/e2e/apimachinery/flowcontrol.go

Pick both:
- https://github.com/kubernetes/kubernetes/pull/96984 
- https://github.com/kubernetes/kubernetes/pull/96966 
Which issue(s) this PR fixes:
Related to #96803 and #96893

UPSTREAM: 96984: APF e2e: wait for steady state before proceeding

---

test/e2e/network/network_policy.go

A variety of IPv6 e2e tests in OpenShift are failing with errors like this:
```
Last 100 log lines of client-can-connect-80-r9gjz:
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
```

UPSTREAM: 96856: e2e network policy enclose IPv6 destinations

---

hack/.staticcheck_failures
test/integration/examples/apiserver_test.go
test/integration/framework/etcd.go
test/integration/framework/test_server.go

(cherry picked from commit 101cdbf932c9728ce164995b637fac84b5618e1b)

UPSTREAM: 97295: Fix staticcheck in test/integration/{examples,framework}

---

REBASE.openshift.md
openshift-hack/images/hyperkube/Dockerfile.rhel

UPSTREAM: <carry>: bump tag version

---

openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
openshift-kube-apiserver/filters/deprecatedapirequest/request_counts_test.go
openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go

Adds more unit test for https://github.com/openshift/kubernetes/pull/663

bug 1949306: UPSTREAM: <carry>: DeprecatedAPIRequestHandler unit tests

---

pkg/kubelet/kuberuntime/kuberuntime_container.go

Fixes crash in killing container
ref https://github.com/kubernetes/kubernetes/pull/101012

Bug 1951042: fix crash when killing container fails

---

pkg/volume/awsebs/aws_util.go

Cherry pick of https://github.com/kubernetes/kubernetes/pull/100500 into OCP 4.8 to fix https://bugzilla.redhat.com/show_bug.cgi?id=1937299

Bug 1937299: Fix mounting partitions on NVMe devices

---

pkg/volume/util/operationexecutor/operation_executor.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1951467
Please note this bug does not exist in 4.7 onwards and hence no cherry-picks are required in those versions.

Bug 1951467: fix loop bug for verify attached volume

---

pkg/kubelet/config/apiserver.go
pkg/kubelet/kubelet.go
pkg/kubelet/kubelet_getters.go

Supersedes #653 
Backport of kubernetes#99336
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1927263

Bug 1927263: UPSTREAM: 99336: kubelet: improve the node informer sync check 

---

pkg/kubelet/kubelet_test.go
pkg/kubelet/kubelet_volumes.go

Upstream Ref: https://github.com/kubernetes/kubernetes/pull/101524

Bug 1952224: kubelet: do not cleanup volumes if pod is being killed

---

pkg/kubelet/eviction/eviction_manager.go
pkg/kubelet/eviction/eviction_manager_test.go

Ref: https://github.com/kubernetes/kubernetes/pull/99095

Bug 1954770: UPSTREAM: 99095: Prevent Kubelet stuck in DiskPressure when imagefs minreclaim is set

---

pkg/kubelet/cm/cpumanager/cpu_manager.go
pkg/kubelet/cm/qos_container_manager_linux.go
pkg/kubelet/config/file.go
pkg/kubelet/config/file_linux.go
pkg/kubelet/managed/managed.go
pkg/kubelet/managed/managed_test.go

Implements https://github.com/openshift/enhancements/pull/741 for the Kubelet.

Bug 1952666: UPSTREAM: <carry>: management workloads enhancement 741(uint64)

---

openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
openshift-kube-apiserver/filters/deprecatedapirequest/request_counts.go
openshift-kube-apiserver/filters/deprecatedapirequest/request_counts_test.go
openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
openshift-kube-apiserver/filters/deprecatedapirequest_filter.go

useragent helps distinguish different containers using the same credentials in a pod.

Bug 1954696: UPSTREAM: <carry>: add apirequestcount useragent

---

pkg/kubelet/configmap/configmap_manager.go
pkg/kubelet/kubelet.go
pkg/kubelet/secret/secret_manager.go
pkg/kubelet/util/manager/watch_based_manager.go
pkg/kubelet/util/manager/watch_based_manager_test.go
test/integration/kubelet/watch_manager_test.go

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1951815
/cc @rphillips @mrunalp

Bug 1951815: UPSTREAM: 99393: kubelet: reduce configmap and secret watch

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go

Bug 1959471: Conformance tests (sysctls) may not be excluded

---

pkg/volume/vsphere_volume/vsphere_volume_util.go

Fixes partially - https://bugzilla.redhat.com/show_bug.cgi?id=1884800

Bug 1884800: Reduce names of vsphere volumes even further

---

plugin/pkg/admission/storage/persistentvolume/label/admission.go
staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1942141
reverts https://github.com/openshift/origin/pull/23578/commits

Bug 1942141: fixes cinder PV labelling

---

plugin/pkg/admission/storage/persistentvolume/label/admission.go
staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go

Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1942146
cc @openshift/sig-storage

Bug 1942146: Fix labels of Cinder PVs

---

REBASE.openshift.md

UPSTREAM: <carry>: update rebase doc

---

pkg/kubelet/DOWNSTREAM_OWNERS

Adding myself to DOWNSTREAM_OWNERS as a reviewer so the bot will pester me.
/cc @rphillips @mrunalp

UPSTREAM: <carry>: kubelet: add ehashman as reviewer

---

openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go

To avoid CPU spikes every interval.

Bug 1950010: UPSTREAM: <carry>: apirequestcount: smear out CR updates over interval

---

test/e2e/auth/node_authn.go

/kind bug
NodeAuthenticator tests are failing in dualstack.
In dualstack, nodes have both IPv4 and IPv6 ip addresses assigned. But Kubelet starts metrics server just picking one of them(first one in the `--node-ip`). However, NodeAuthenticator tests try to send requests to all of IP addresses and these tests are failing in dualstack. This PR filters node IPs according to the first IP family(which kubelet starts server to listen). 
This test will fail for IPv6 until https://github.com/openshift/origin/pull/26140 is merged. However, this PR can be safely merged, because these two tests have not been enabled for IPv6 configuration yet.
```release-note
NONE
```

UPSTREAM: 103050: Bug 1975325: Fix NodeAuthenticator tests in dual stack

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/controller-manager/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kubectl/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
vendor/modules.txt

contains this fix: https://github.com/openshift/apiserver-library-go/pull/50 for https://bugzilla.redhat.com/show_bug.cgi?id=1925180
Fixes # 
- https://bugzilla.redhat.com/show_bug.cgi?id=1925180
- https://bugzilla.redhat.com/show_bug.cgi?id=1976775
```release-note
NONE
```
```docs
```

UPSTREAM: <drop>: bump(apiserver-library-go)

---

staging/src/k8s.io/legacy-cloud-providers/vsphere/shared_datastore.go
staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/virtualmachine.go
staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1951727

Bug 1951727: Speed up PV provisioning for vsphere driver (ocp-4.6)

---

staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1957133
cc @openshift/sig-storage

Bug 1957133: do not throw error when we can't get canonical path

---

staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1973766
cc @openshift/sig-storage

Bug 1973766: 4.7: Do not throw error when we can't get canonical path

---

staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go

still seeing failures in CI (https://search.ci.openshift.org/?search=clusteroperator%2Fopenshift-apiserver+condition%2FAvailable+status%2FFalse+reason%2FAPIServicesAvailable.*Get.*dial&maxAge=24h&context=1&type=junit&name=periodic.*4.9.*upgrade&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
looking at https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-e2e-gcp-upgrade-build02/1431627932949811200/artifacts/e2e-gcp-upgrade-build02/gather-extra/artifacts/pods/openshift-kube-apiserver_kube-apiserver-ci-op-wp4pwrvw-a78f0-vgx7g-master-0_kube-apiserver.log I have realized the availability might change while we are performing the checks. This PR marks the availability of the server before checking the aggregate APIs …

Bug 1948089: openshift-apiserver should not set Available=False APIServicesAvailable on update

---

pkg/kubelet/kubelet_pods.go
pkg/kubelet/pod_workers.go
pkg/kubelet/pod_workers_test.go

Upstream Ref: https://github.com/kubernetes/kubernetes/pull/104577

Bug 1997657: UPSTREAM: 104577: kubelet: Admission must exclude completed pods and avoid races

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apimachinery/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/client-go/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/cluster-bootstrap/go.sum
staging/src/k8s.io/code-generator/go.sum
staging/src/k8s.io/component-base/go.sum
staging/src/k8s.io/cri-api/go.sum
staging/src/k8s.io/csi-translation-lib/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kube-controller-manager/go.sum
staging/src/k8s.io/kube-proxy/go.sum
staging/src/k8s.io/kube-scheduler/go.sum
staging/src/k8s.io/kubectl/go.sum
staging/src/k8s.io/kubelet/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.sum
staging/src/k8s.io/metrics/go.sum
staging/src/k8s.io/sample-apiserver/go.sum
staging/src/k8s.io/sample-cli-plugin/go.sum
staging/src/k8s.io/sample-controller/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
vendor/modules.txt

contains fix openshift/apiserver-library-go#56 for a backport https://bugzilla.redhat.com/show_bug.cgi?id=1981784
Fixes #
- https://bugzilla.redhat.com/show_bug.cgi?id=1981784
```release-note
NONE
```
```docs
```

Bug 1981784: UPSTREAM: <drop>: bump(apiserver-library-go)

---

pkg/kubelet/kubelet.go
pkg/kubelet/kubelet_pods.go
pkg/kubelet/kubelet_test.go

ref: https://github.com/kubernetes/kubernetes/pull/104817

Bug 2003269: UPSTREAM: 104817:  kubelet: Rejected pods should be filtered from admission

---

pkg/proxy/iptables/proxier_openshift.go
pkg/proxy/userspace/proxier.go
pkg/proxy/userspace/proxier_openshift.go

Bug 2002290: [4.8] userspace: Don't sync every iptables rule on every service change

---

staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go

MCO PR https://github.com/openshift/machine-config-operator/pull/2764

UPSTREAM: <carry>: add control plane to allowed roles

---

openshift-kube-apiserver/admission/admissionenablement/admission_config.go
openshift-kube-apiserver/admission/namespaceconditions/decorator.go

SCC can be skipped by setting a namespace label `security.openshift.io/disable-securitycontextconstraints = true`.  This is useful for disabling SCC and using PodSecurity admission instead.

UPSTREAM: <carry>: allow SCC to be disabled on a per-namespace basis

---

pkg/kubelet/kubelet_pods.go
pkg/kubelet/kubelet_pods_test.go
pkg/kubelet/status/status_manager.go
pkg/kubelet/status/status_manager_test.go
test/e2e/node/pods.go

Backports https://github.com/kubernetes/kubernetes/pull/105462

Bug 1997478: Ensure terminal pods maintain terminal status

---

pkg/kubelet/kubelet_pods.go
pkg/kubelet/kubelet_pods_test.go
pkg/kubelet/status/status_manager.go
pkg/kubelet/status/status_manager_test.go
test/e2e/node/pods.go

[release-4.9] Bug 2011050: Ensure terminal pods maintain terminal status

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/controller-manager/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kubectl/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagereferencemutators/pods.go
vendor/modules.txt

/kind bug
Fixes BZ 2000216.
```release-note
```
```docs
```

Bug 2000216: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs

---

openshift-hack/lib/build/version.sh

/assign @josefkarasek @vrutkovs

Bug 2021936: Read k8s version from hyperkube Dockerfile

---

pkg/kubelet/kuberuntime/kuberuntime_manager.go
pkg/kubelet/metrics/metrics.go

Backport of https://github.com/kubernetes/kubernetes/pull/105213

Bug 2007495: UPSTREAM: 105213: remove StartedPodsErrorsTotal metrice message

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/controller-manager/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kubectl/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
vendor/modules.txt

/kind bug
This is a cherry-pick of #1033.
Fixes BZ 2020644.
```release-note
```
```docs
```

Bug 2020644: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs

---

go.mod
go.sum
staging/src/k8s.io/api/go.mod
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.mod
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.mod
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.mod
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.mod
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/controller-manager/go.mod
staging/src/k8s.io/controller-manager/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kubectl/go.mod
staging/src/k8s.io/kubectl/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.mod
staging/src/k8s.io/legacy-cloud-providers/go.sum
vendor/github.com/google/cadvisor/container/crio/factory.go
vendor/github.com/google/cadvisor/container/factory.go
vendor/github.com/google/cadvisor/container/libcontainer/handler.go
vendor/modules.txt

Signed-off-by: Harshal Patil <harpatil@redhat.com>
/kind bug
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1978528, https://bugzilla.redhat.com/show_bug.cgi?id=2016175
```release-note
None
```
```docs
```

Bug 1978528: UPSTREAM: <carry>: bump cadvisor for 2957, 2999 and 2979 upstream patches

---

REBASE.openshift.md
openshift-hack/rebase.sh

@josefkarasek and I wanted to share the rebase script we've recently used for the 4.6 rebase in #1035 
We're going to work on automating this a bit more, especially around the conflict resolution and a bot after the feature freeze. We'll share a design doc with you soon (cc @sherine-k).
/kind feature
/label tide/merge-method-squash

Rebase Automation Script

---

pkg/volume/util/subpath/subpath_linux.go
pkg/volume/util/subpath/subpath_linux_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2008532
/sig storage

Bug 2008532: Fix subpath sources check

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/kubectl/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
vendor/modules.txt

/kind bug
This is a cherry-pick of #1050.
Fixes BZ 2022188.
```release-note
```
```docs
```

Bug 2022188: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs

---

pkg/volume/util/subpath/subpath_linux.go
pkg/volume/util/subpath/subpath_linux_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2024967

Bug 2024967: Fix subpath unmount error

---

.ci-operator.yaml

UPSTREAM: <drop>: revert to go1.16

---

pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/volume/csi/csi_mounter.go
pkg/volume/util/hostutil/fake_hostutil.go
pkg/volume/util/hostutil/hostutil_linux.go
pkg/volume/util/hostutil/hostutil_linux_test.go

When GetSELinuxSupport() fails, don't assume a mounted filesystem does not support SELinux at all. Try again instead in the next SetUp retry.

[4.8] Bug 2022741: UPSTREAM: 106260: Don't guess SELinux support on error

---

pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/volume/csi/csi_mounter.go
pkg/volume/util/hostutil/BUILD
pkg/volume/util/hostutil/fake_hostutil.go
pkg/volume/util/hostutil/hostutil_linux.go
pkg/volume/util/hostutil/hostutil_linux_test.go

When GetSELinuxSupport() fails, don't assume a mounted filesystem does not support SELinux at all. Try again instead in the next SetUp retry.

[4.7] Bug 2022720: UPSTREAM: 106261: Don't guess SELinux support on error

---

pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/volume/csi/csi_mounter.go
pkg/volume/util/hostutil/BUILD
pkg/volume/util/hostutil/fake_hostutil.go
pkg/volume/util/hostutil/hostutil_linux.go
pkg/volume/util/hostutil/hostutil_linux_test.go

When GetSELinuxSupport() fails, don't assume a mounted filesystem does not support SELinux at all. Try again instead in the next SetUp retry.

[4.6] Bug 2023306: UPSTREAM: 106261: Don't guess SELinux support on error

---

pkg/volume/util/subpath/subpath_linux.go
pkg/volume/util/subpath/subpath_linux_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2024995

Bug 2024995: Fix subpath source check

---

pkg/volume/util/subpath/subpath_linux.go
pkg/volume/util/subpath/subpath_linux_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2024996

Bug 2024996: Fix subpath source check

---

test/e2e/storage/vsphere/config.go

Bug 2034705: UPSTREAM 107136: Don't log vSphere configuration data in storage e2e tests

---

cmd/watch-termination/main.go

fix watch-termination to create termination.log file with restricted permissions.
watch-termination uses lumberjack for logging.
it creates permissive files by default 0644 and at the moment there is no way to specify
permission while creating a file, the only way to workaround is to create a file before.
this pr touches a file with restrictive permissions 0600 and relies on the fact that
lumberjack respects and copies permission over if the file already exists.

Bug 2001442: empty termination.log file for the kube-apiserver has too permissive mode

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/client-go/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/component-base/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kube-controller-manager/go.sum
staging/src/k8s.io/kube-proxy/go.sum
staging/src/k8s.io/kube-scheduler/go.sum
staging/src/k8s.io/kubectl/go.sum
staging/src/k8s.io/kubelet/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.sum
staging/src/k8s.io/metrics/go.sum
staging/src/k8s.io/sample-apiserver/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
vendor/modules.txt

/kind bug
This is a cherry-pick of #1073.
Fixes BZ 2026380.
```release-note
```
```docs
```

Bug 2026380: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs

---

staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go

The OpenStack secret is not guaranteed to be present at the time
kube-controller-manager is initialised.

Bug 2004542: UPSTREAM: 89885: SQUASH: Retry fetching clouds.conf

---

test/e2e/storage/testsuites/snapshottable.go

Fix snapshot e2e failures
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2040793

Bug 2040793: Fix ordering issues with snapshot e2e

---

pkg/kubelet/pod_workers.go
pkg/kubelet/pod_workers_test.go
test/e2e_node/mirror_pod_grace_period_test.go

Backports upstream static pod fix https://github.com/kubernetes/kubernetes/pull/107900

[release-4.10] Bug 2050250: Upstream 107900 static pod fix

---

pkg/kubelet/kuberuntime/kuberuntime_container.go
pkg/kubelet/kuberuntime/kuberuntime_manager.go
pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
vendor/modules.txt

Upstream Ref: https://github.com/kubernetes/kubernetes/pull/108164

Bug 2050250: UPSTREAM: 108164: Ignore container notfound error while getPodstatuses

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>
Fixes #
```release-note
```
```docs
```

Bug 1945329: enable should drop INVALID conntrack entries test

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
pkg/kubelet/kubelet.go
pkg/kubelet/kubelet_pods.go
pkg/kubelet/kubelet_test.go
pkg/kubelet/pod_workers.go
pkg/kubelet/pod_workers_test.go
pkg/kubelet/runonce.go
pkg/kubelet/status/status_manager.go
pkg/kubelet/status/status_manager_test.go
pkg/kubelet/status/testing/fake_pod_deletion_safety.go
pkg/kubelet/status/testing/mock_pod_status_provider.go
test/e2e/apps/job.go
test/e2e/node/pods.go
test/e2e_node/node_shutdown_linux_test.go

Ref: https://github.com/kubernetes/kubernetes/pull/108366

Bug 2022507: Backport 108366: OutofCpu Fixes

---

test/e2e/scheduling/priorities.go

UPSTREAM: 106454: test/e2e: fix e2e tests for restricted policy

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
pkg/kubelet/kubelet.go
pkg/kubelet/kubelet_pods.go
pkg/kubelet/kubelet_test.go
pkg/kubelet/pod_workers.go
pkg/kubelet/pod_workers_test.go
pkg/kubelet/runonce.go
pkg/kubelet/status/status_manager.go
pkg/kubelet/status/status_manager_test.go
pkg/kubelet/status/testing/fake_pod_deletion_safety.go
pkg/kubelet/status/testing/mock_pod_status_provider.go
test/e2e/apps/job.go
test/e2e/node/pods.go
test/e2e_node/node_shutdown_linux_test.go

ref: https://github.com/kubernetes/kubernetes/pull/108723

[release-4.10] Bug 2065774: Backport 108723 OutofCpu Fixes

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
pkg/kubelet/kubelet.go
pkg/kubelet/kubelet_pods.go
pkg/kubelet/kubelet_test.go
pkg/kubelet/pod_workers.go
pkg/kubelet/pod_workers_test.go
pkg/kubelet/runonce.go
pkg/kubelet/status/status_manager.go
pkg/kubelet/status/status_manager_test.go
pkg/kubelet/status/testing/fake_pod_deletion_safety.go
pkg/kubelet/status/testing/mock_pod_status_provider.go
test/e2e/apps/job.go
test/e2e/node/pods.go
test/e2e_node/node_shutdown_linux_test.go

ref: https://github.com/kubernetes/kubernetes/pull/108749

[release-4.9] Bug 2065786: Backport 108366 OutofCpu Fixes

---

openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go

Update the list of deprecated APIs marked for removal base on the latest [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide).
/kind bug
Keep list of deprecated APIs up-to-date.
Fixes #
```release-note
```
```docs
```

UPSTREAM: <carry>: update list of deprecated apis

---

pkg/kubelet/kubelet.go
pkg/kubelet/pod/pod_manager.go
pkg/kubelet/util/manager/cache_based_manager.go
pkg/kubelet/util/manager/cache_based_manager_test.go

ref: https://github.com/kubernetes/kubernetes/pull/107821
and
ref: https://github.com/kubernetes/kubernetes/pull/107831

Bug 1999325: Backport 107821 and 107831

---

pkg/features/kube_features.go
test/integration/job/job_test.go

/assign @deads2k 
/cc @tkashem

Bug 2075621: UPSTREAM: 109487: Disable JobTrackingWithFinalizers due to unresolved bug

---

pkg/kubelet/kubelet.go
pkg/kubelet/pod/pod_manager.go
pkg/kubelet/util/manager/cache_based_manager.go
pkg/kubelet/util/manager/cache_based_manager_test.go

[release-4.9] Bug 2075704: Backport 107821 and 107831

---

pkg/kubelet/kubelet.go
pkg/kubelet/pod/pod_manager.go
pkg/kubelet/util/manager/cache_based_manager.go
pkg/kubelet/util/manager/cache_based_manager_test.go

Reverts openshift/kubernetes#1242

[release-4.9] Bug 2075704: Revert Backport 107821 and 107831

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
pkg/api/v1/pod/util.go
pkg/api/v1/pod/util_test.go
pkg/controller/endpoint/endpoints_controller.go
pkg/controller/endpoint/endpoints_controller_test.go
pkg/controller/endpointslice/reconciler.go
pkg/controller/util/endpoint/controller_utils.go
pkg/controller/util/endpoint/controller_utils_test.go
pkg/kubelet/status/status_manager.go
test/e2e/network/service.go
test/e2e/node/pods.go

Backport of https://github.com/kubernetes/kubernetes/pull/110258

Bug 2094954: UPSTREAM: 110258: Fix pod eviction ip

---

pkg/kubelet/cm/containermap/container_map.go
pkg/kubelet/cm/cpumanager/cpu_manager.go
pkg/kubelet/cm/memorymanager/memory_manager.go

fixes leak in containerMap https://github.com/kubernetes/kubernetes/pull/109103

Bug 2065749: UPSTREAM: 109103: cpu/memory manager containerMap memory leak

---

pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2082773

Bug 2082773: Fix resizing of ephemeral volumes

---

pkg/kubelet/cm/containermap/container_map.go
pkg/kubelet/cm/cpumanager/cpu_manager.go
pkg/kubelet/cm/memorymanager/memory_manager.go

Cherry pick of https://github.com/openshift/kubernetes/pull/1318

[release-4.9] Bug 2106655: UPSTREAM: 109103: cpu/memory manager containerMap memory leak

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/controller-manager/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kubectl/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/admission/quota/clusterresourcequota/admission.go
vendor/modules.txt

kind/cleanup
It adds the plugin name to an error message to help when debugging
Fixes #
```release-note
NONE
```
```docs
```

trt-393: add plugin name to caches not synchronized error

---

pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2104344

Bug 2104344: Fix resizing of ephemeral volumes

---

pkg/controller/podautoscaler/horizontal.go
pkg/controller/podautoscaler/horizontal_test.go

Cherry-pick of https://github.com/kubernetes/kubernetes/pull/109058
When calculating the scale-up/scale-down limit, the number of replicas
at the start of the scaling policy period is calculated correctly by
taken into account the number of scaled-up and scaled-down replicas.
/kind bug

Bug 2041317: Fix replica calculation at start of HPA scaling policy period

---

test/e2e/framework/pod/wait.go
test/e2e/storage/ubernetes_lite_volumes.go

UPSTREAM: 113135: Wait for pod not running or gone in storage tests

---

test/e2e/storage/testsuites/ephemeral.go

Fixes https://issues.redhat.com/browse/OCPBUGS-2991

Bug OCPBUGS-2991: Disable expansion in SC, if driver does not support it

---

test/e2e/storage/testsuites/ephemeral.go

Fixes bug https://issues.redhat.com/browse/OCPBUGS-2927

Bug OCPBUGS-2927: Disable expansion in SC, if driver does not support it

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go

- UPSTREAM: <carry>: disable tests dependent on StackDriver
- UPSTREAM: <drop>: update generated code

disable tests dependent on StackDriver

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/controller-manager/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kubectl/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
vendor/modules.txt

[4.11] OCPBUGS-6683: add message about possibly working with restricted SCC

---

go.mod
go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/seccomp/strategy.go
vendor/modules.txt

[4.12] OCPBUGS-5769: scc admission - seccomp profiles fix

---

pkg/securitycontext/accessors.go
pkg/securitycontext/accessors_test.go

/assign @openshift/openshift-team-auth 
/cc @deads2k

OCPBUGS-7267: add SeccompProfile to Pod and Container accessors/mutators

---

go.mod
go.sum
plugin/pkg/admission/security/podsecurity/patch_podspecextractor.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/patched_sc_accessors.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
vendor/modules.txt

/cc @openshift/openshift-team-auth  @deads2k 
It seems that there are still some issues as outlined in the linked BZ. I see that for some reason, I hardcoded a specific seccompProfile to the tested Deployment in the e2e test. I have no idea why. However, that is the very spot that's failing at this moment.
Adding some more logging to help me figure out what's going on.

OCPBUGS-7267: More fixes to SCC PSa extractor

---

pkg/kubelet/kubelet_pods_test.go
pkg/kubelet/pod_workers.go

OCPBUGS-2474: UPSTREAM: 116995: kubelet: Ensure pods that have not started track pendingUpdate

---

test/e2e/apps/statefulset.go
test/e2e/framework/statefulset/wait.go

UPSTREAM: 117893:  When expecting pods count only active ones

---

go.mod
go.sum
staging/src/k8s.io/api/go.mod
staging/src/k8s.io/apiextensions-apiserver/go.mod
staging/src/k8s.io/apiserver/go.mod
staging/src/k8s.io/component-base/go.mod
staging/src/k8s.io/component-helpers/go.mod
staging/src/k8s.io/kms/go.mod
staging/src/k8s.io/kube-aggregator/go.mod
vendor/github.com/google/cadvisor/container/crio/handler.go
vendor/modules.txt

/kind bug
Fixes # https://issues.redhat.com/browse/OCPBUGS-14427
```release-note
None
```
Upstream PR - https://github.com/kubernetes/kubernetes/pull/118383
```docs
```

OCPBUGS-4053: UPSTREAM: 118383: bump cadvisor for upstream patch 3301

---

cmd/kube-proxy/app/server_openshift.go
pkg/proxy/iptables/proxier.go
pkg/proxy/iptables/proxier_openshift.go
pkg/proxy/iptables/proxier_test.go

Bring in sdn upstream carry commits
No  conflicts

Sdn 4.14 kubernetes 1.27.1 upstream carries

---

go.mod
go.sum
staging/src/k8s.io/api/go.mod
staging/src/k8s.io/apiextensions-apiserver/go.mod
staging/src/k8s.io/apiserver/go.mod
staging/src/k8s.io/cli-runtime/go.mod
staging/src/k8s.io/cloud-provider/go.mod
staging/src/k8s.io/kubectl/go.mod
staging/src/k8s.io/legacy-cloud-providers/go.mod
vendor/github.com/google/cadvisor/container/crio/handler.go
vendor/modules.txt

/kind bug 
Fixes # https://issues.redhat.com/browse/OCPBUGS-14745
```release-note
None
```
```docs
```

OCPBUGS-14745: [release-4.12] UPSTREAM: 118383: bump cadvisor for upstream patch 3301

---

go.mod
go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
vendor/modules.txt

This pulls in https://github.com/openshift/apiserver-library-go/pull/110
/cc @soltysh @stlaz

OCPBUGS-7181: UPSTREAM: <drop>: bump apiserver-library-go

---

go.mod
go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
vendor/modules.txt

[4.13] OCPBUGS-8738: bump apiserver-lib-go

---

staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go

Carrying https://github.com/kubernetes/kubernetes/pull/118881

OCPBUGS-15726: UPSTREAM: 118881: fix openapi/v3 non local apiservices aggregation

---

openshift-hack/images/os/Dockerfile
test/e2e/storage/flexvolume_mounted_volume_resize.go
test/e2e/storage/mounted_volume_resize.go

https://github.com/openshift/kubernetes/pull/1512 - Slightly modified for framework compatibility

[release-4.6] Fix mounted volume expansion tests

---

go.mod
go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
vendor/modules.txt

backport of https://github.com/openshift/kubernetes/pull/1619
/assign @s-urbaniak

[4.11] OCPBUGS-8736: UPSTREAM: <drop>: bump apiserver-library-go

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/cli-runtime/go.sum
staging/src/k8s.io/cloud-provider/go.sum
staging/src/k8s.io/controller-manager/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
staging/src/k8s.io/kubectl/go.sum
staging/src/k8s.io/legacy-cloud-providers/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
vendor/modules.txt

backport of https://github.com/openshift/kubernetes/pull/1627
/assign @s-urbaniak

[4.10] OCPBUGS-8735: UPSTREAM: <drop>: bump apiserver-library-go

---

pkg/kubelet/cm/cgroup_manager_linux.go

/kind bug 
If we call mgr.Apply() first, libcontainer's cpusetCopyIfNeeded() will copy the parent cpuset and set load balancing to 1 by default. This causes the kernel to set the cpus to not load balanced for a brief moment which causes churn.
instead, create the cgroup and set load balance, then have Apply() copy the values into it.
Fixes #
```release-note
fix a bug in cpuset load balancing where cpusets flip between load balanced and not due to an ordering issue.
```
```docs
```

OCPBUGS-17654: cm: reorder setting of sched_load_balance for sandbox slice

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go

UPSTREAM: <carry>: disable test removed in 1.28

---

cmd/watch-termination/main.go

xref: https://issues.redhat.com/browse/OCPBUGS-15783
Does this commit seem to be lost during rebase(s) ?

OCPBUGS-16080: UPSTREAM: <carry>: watch-termination: termination.log file

---

pkg/kubelet/cm/cgroup_manager_linux.go

Fixes #
```release-note
```
```docs
```

OCPBUGS-19666: kubelet/cm: use MkdirAll when creating cpuset to ignore file exists error

---

cmd/kubelet/app/options/options.go
plugin/pkg/admission/noderestriction/admission.go
staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go

/kind bug
Fixes # https://issues.redhat.com/browse/OCPBUGS-20113
```release-note
```
```docs
```

[release-4.12] OCPBUGS-20113: UPSTREAM: <carry>: Do not allow nodes to set forbidden openshift labels

---

cmd/kube-proxy/app/server_openshift.go
pkg/proxy/iptables/proxier.go
pkg/proxy/iptables/proxier_openshift.go
pkg/proxy/iptables/proxier_test.go

Fixes #
```release-note
```
```docs
```

SDN-4123: Sdn 4.15 kubernetes 1.28.3

---

staging/src/k8s.io/mount-utils/mount_windows.go

Fixes #
```release-note
```
```docs
```

OCPBUGS-22724: UPSTREAM: 121881: Use golang library instead of mklink

---

staging/src/k8s.io/mount-utils/mount_windows.go

Fixes #
```release-note
```
```docs
```

[release-4.14] OCPBUGS-23286: UPSTREAM: 121881: Use golang library instead of mklink

---

staging/src/k8s.io/mount-utils/mount_windows.go

Fixes #
```release-note
```
```docs
```

[release-4.13] OCPBUGS-23287: UPSTREAM: 121881: Use golang library instead of mklink

---

staging/src/k8s.io/mount-utils/mount_windows.go

Fixes #
```release-note
```
```docs
```

[release-4.12] OCPBUGS-23288: UPSTREAM: 121881: Use golang library instead of mklink

---

staging/src/k8s.io/mount-utils/mount_windows.go

Fixes #
```release-note
```
```docs
```

[release-4.11] OCPBUGS-23289: UPSTREAM: 121881: Use golang library instead of mklink

---

staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/utils.go
staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/utils_test.go

https://issues.redhat.com/browse/OCPBUGS-25767
/cc @openshift/storage @soltysh

OCPBUGS-25767: legacy-cloud-providers: prevent index out-of-range in getNextUnitNumber

---

staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/utils.go
staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/utils_test.go

https://issues.redhat.com/browse/OCPBUGS-25214
/cc @openshift/storage @soltysh

OCPBUGS-25214: legacy-cloud-providers: prevent index out-of-range in getNextUnitNumber

---

test/e2e/framework/internal/unittests/bugs/bugs_test.go
test/e2e/framework/internal/unittests/list-labels/listlabels_test.go
test/e2e/framework/internal/unittests/list-tests/listtests_test.go
test/e2e/framework/test_context.go

/assign @sairameshv 
/hold 
until we confirm the signal in https://github.com/openshift/origin/pull/28488

OCPNODE-1895: temporarily disable reporting e2e text bugs

---

test/e2e/framework/job/fixtures.go
test/e2e/upgrades/apps/job.go

/assign @sairameshv 
/hold 
until upstream PR gets tagged

OCPNODE-1892: UPSTREAM: 122643: Add a new neverTerminate job behavior just for upgrade

---

pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/kubelet/volumemanager/reconciler/reconciler_test.go
pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
pkg/volume/testing/testing.go
pkg/volume/util/operationexecutor/operation_executor.go
pkg/volume/util/operationexecutor/operation_generator.go

Fixes https://issues.redhat.com/browse/OCPBUGS-23896

OCPBUGS-23896:  Fix device uncertain errors on reboot

---

test/e2e/apimachinery/validatingadmissionpolicy.go

/assign @sairameshv 
/hold 
for upstream to merge first

OCPNODE-1892: UPSTREAM: 122683: Use v1beta1 endpoints when cleaning up ValidatingAdmissionPolicies

---

pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/kubelet/volumemanager/reconciler/reconciler_test.go
pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
pkg/volume/testing/testing.go
pkg/volume/util/operationexecutor/operation_executor.go
pkg/volume/util/operationexecutor/operation_generator.go

fixes https://issues.redhat.com/browse/OCPBUGS-25812

OCPBUGS-25812: Fix device uncertain errors on reboot - 4.15

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go

OCPNODE-1892: UPSTREAM: <carry>: update test rules

---

pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/kubelet/volumemanager/reconciler/reconciler_test.go
pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
pkg/volume/testing/testing.go
pkg/volume/util/operationexecutor/operation_executor.go
pkg/volume/util/operationexecutor/operation_generator.go

Fixes https://issues.redhat.com/browse/OCPBUGS-25813

OCPBUGS-25813: Fix uncertain device in 4.14

---

go.mod
go.sum
pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/kubelet/volumemanager/reconciler/reconciler_test.go
pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
pkg/volume/testing/testing.go
pkg/volume/util/operationexecutor/operation_executor.go
pkg/volume/util/operationexecutor/operation_generator.go
vendor/modules.txt

Fixes https://issues.redhat.com/browse/OCPBUGS-25814

OCPBUGS-25814: Fix device uncertain errors on reboot - 4.13

---

openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go

Updating the logic for pod admission to allow a pod creation with workload partitioning annotations to be run in a namespace that has no workload allow annoations.
The pod will be stripped of its workload annotations and treated as if it were normal, a warning annoation will be placed to note the behavior on the pod.
See more info https://issues.redhat.com/browse/CNF-10581

OCPBUGS-24606: UPSTREAM: <carry>: Update management webhook pod admission logic

---

pkg/kubelet/volumemanager/cache/actual_state_of_world.go
pkg/kubelet/volumemanager/reconciler/reconciler_test.go
pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
pkg/volume/testing/testing.go
pkg/volume/util/operationexecutor/operation_executor.go
pkg/volume/util/operationexecutor/operation_generator.go

https://issues.redhat.com/browse/OCPBUGS-25815

OCPBUGS-25815:  Fix device uncertain errors on reboot 4.12

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go

OCPBUGS-16760: permanently disable NodeLogQuery e2e test

---

.synk

Reverts openshift/kubernetes#1824

NO-JIRA: Revert "OCPBUGS-24404: add ignore for SAST scan"

---

pkg/kubelet/volumemanager/reconciler/reconciler_test.go
pkg/volume/csi/expander.go
pkg/volume/testing/testing.go
pkg/volume/util/operationexecutor/operation_generator.go
pkg/volume/util/types/types.go

Fixes https://issues.redhat.com/browse/OCPBUGS-10996

OCPBUGS-10996: Fix race condition between resizer and kubelet

---

pkg/kubelet/managed/managed.go
pkg/kubelet/managed/managed_test.go

when static pods have workload partitioning enabled we should not alter their resources if they are Guaranteed QoS, this change adds a check for Guaranteed QoS
Fixes #
```release-note
```
```docs
```

OCPBUGS-31663: UPSTREAM: <carry>: add management workload check for guaranteed qos

---

openshift-kube-apiserver/admission/scheduler/nodeenv/admission.go
openshift-kube-apiserver/admission/scheduler/nodeenv/admission_test.go

cherry-pick of https://github.com/openshift/kubernetes/pull/1787

[release-4.14] OCPBUGS-29924: UPSTREAM: <carry>: openshift-kube-apiserver: add kube-apiserver patches

---

openshift-hack/images/tests/Dockerfile.rhel

OCPBUGS-20097: Migrate tools image to RHEL9

---

openshift-hack/images/installer-kube-apiserver-artifacts/Dockerfile.rhel

This is needed for the s390x/ppc64le arches since we just cross-compile to linux amd/arm64.
/kind bug
Without ppc64le/s390x native artifacts, installer builds in the release pipeline fail when trying to copy the binaries from the artifacts image.
Fixes #
```release-note
NONE
```
```docs
```

no-jira: UPSTREAM <carry>: add native build to installer image

---

test/e2e/apps/daemon_set.go

that are terminated by the test

OCPBUGS-32934: UPSTREAM: 124795: e2e: DaemonSet maxSurge test should account for terminated pods

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/annotate/rules.go

API-1783: UPSTREAM: <carry>: skip storage tests

---

pkg/scheduler/schedule_one.go
pkg/scheduler/schedule_one_test.go
test/integration/scheduler/scheduler_test.go

OCPBUGS-34593: UPSTREAM: 124933: [Scheduler] Use allNodes when calculating nextStartNodeIndex

---

hack/make-rules/verify.sh

Followup to https://github.com/openshift/kubernetes/pull/1992

OCPBUGS-35553: Disable vulncheck

---

pkg/kubelet/kubelet.go
test/e2e_node/pod_ips.go

Upstream Patch: https://github.com/kubernetes/kubernetes/pull/125404

OCPBUGS-37111: UPSTREAM: 125404: Fix that PodIP field is temporarily removed for a terminal pod

---

openshift-hack/cmd/go-imports-diff/main.go
openshift-hack/verify-test-annotations.sh

NO-JIRA: add tool to validate test packages imported

---

pkg/kubelet/kubelet.go
pkg/util/filesystem/defaultfs.go
pkg/util/filesystem/util_unix.go
pkg/util/filesystem/util_windows.go
pkg/util/filesystem/util_windows_test.go

Upstream patch: 
- https://github.com/kubernetes/kubernetes/pull/126104

OCPBUGS-37281: UPSTREAM: 126104: Add funcs in pkg/filesystem/util to set file permissions on Windows and update container log dir perms

---

test/e2e_node/container_metrics_test.go
test/e2e_node/resource_metrics_test.go

This pr brings in https://github.com/kubernetes/kubernetes/pull/126213 to verify expected metrics.

NO-JIRA: UPSTREAM: 126213: add test about container metrics from cadvisor

---

DOWNSTREAM_OWNERS

NO-JIRA: update downstream owners

---

pkg/kubelet/kuberuntime/logs/logs.go
pkg/kubelet/kuberuntime/logs/logs_test.go

/kind bug
Fixes #[OCPBUGS-38861](https://issues.redhat.com/browse/OCPBUGS-38861)
```release-note
fix log rotations
```
```docs
```

[release-4.15]: OCPBUGS-38861: Upstream: 115702 kubelet: output log even file is rotated

---

go.mod
go.sum
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/component-base/go.sum
staging/src/k8s.io/component-helpers/go.sum
staging/src/k8s.io/kube-aggregator/go.sum
vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sysctl/mustmatchpatterns.go
vendor/modules.txt

To fix the safe sysctls list in OCP.
Addresses: https://issues.redhat.com/browse/OCPBUGS-38149
```release-note
None
```
```docs
```

NO-JIRA: UPSTREAM:<drop>: bump openshift/library-go@4d55b6d

---

openshift-hack/images/hyperkube/Dockerfile.rhel

WRKLDS-1449: Update Hyperkube Dockerfile with the right Kubernetes version

---

CHANGELOG/CHANGELOG-1.31.md
cmd/kube-controller-manager/app/controllermanager_test.go
cmd/kube-controller-manager/app/core.go
openshift-hack/images/hyperkube/Dockerfile.rhel
pkg/controlplane/controller/leaderelection/run_with_leaderelection.go
pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
pkg/scheduler/schedule_one_test.go
pkg/scheduler/testing/wrappers.go
staging/src/k8s.io/apiserver/pkg/server/config.go
staging/src/k8s.io/apiserver/pkg/server/config_test.go
staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go
staging/src/k8s.io/cloud-provider/controllers/service/controller.go
test/instrumentation/documentation/documentation-list.yaml
test/instrumentation/documentation/documentation.md

[release-4.18] OCPBUGS-45117: Update to Kubernetes 1.31.3

---

CHANGELOG/CHANGELOG-1.30.md
openshift-hack/images/hyperkube/Dockerfile.rhel
pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
pkg/scheduler/schedule_one_test.go
pkg/scheduler/testing/wrappers.go
staging/src/k8s.io/apiserver/pkg/server/config.go
staging/src/k8s.io/apiserver/pkg/server/config_test.go

Bump kubernetes version to 1.30.7
/cc @bertinatto

OCPBUGS-46002: Bump k8s api to 1.30.7

---

CHANGELOG/CHANGELOG-1.29.md
build/dependencies.yaml
cluster/gce/manifests/etcd.manifest
cluster/gce/upgrade-aliases.sh
cluster/images/etcd/Makefile
cluster/images/etcd/migrate/options.go
cmd/kubeadm/app/constants/constants.go
hack/lib/etcd.sh
openshift-hack/images/hyperkube/Dockerfile.rhel
pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
pkg/scheduler/schedule_one_test.go
pkg/scheduler/testing/wrappers.go
staging/src/k8s.io/apiserver/pkg/server/config.go
staging/src/k8s.io/apiserver/pkg/server/config_test.go
staging/src/k8s.io/legacy-cloud-providers/azure/azure_blobDiskController_test.go
staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
test/e2e/framework/providers/gcp.go
test/utils/image/manifest.go

Bump kubernetes version to 1.29.11
/cc @bertinatto

OCPBUGS-46003: Bump k8s api to 1.29.11

---

test/e2e/node/pod_admission.go

This is a cherry-pick from upstream to fix the test.
I will create a follow-up PR to enable the test that has been skipped.
The test is validated in this PR https://github.com/openshift/kubernetes/pull/2220 .
Fixes #
```release-note
```
```docs
```

OCPBUGS-45274: UPSTREAM: 130097: Modify how to check the status

---

staging/src/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go
staging/src/k8s.io/client-go/util/cert/cert.go

Extend loopback certificate validity to 3 years to match upstream

OCPBUGS-54208: UPSTREAM: 130047: adjusting loopback certificate validity in kube-apiserver

---

openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
openshift-hack/e2e/kube_e2e_test.go

#2255 removed the generation of annotations by mistake.
/assign @smg247

NO-JIRA: Fix generation of test names

---

go.mod
go.sum
staging/src/k8s.io/api/go.mod
staging/src/k8s.io/api/go.sum
staging/src/k8s.io/apiextensions-apiserver/go.mod
staging/src/k8s.io/apiextensions-apiserver/go.sum
staging/src/k8s.io/apiserver/go.mod
staging/src/k8s.io/apiserver/go.sum
staging/src/k8s.io/component-base/go.mod
staging/src/k8s.io/component-base/go.sum
staging/src/k8s.io/component-helpers/go.mod
staging/src/k8s.io/component-helpers/go.sum
staging/src/k8s.io/kube-aggregator/go.mod
staging/src/k8s.io/kube-aggregator/go.sum
vendor/github.com/google/cadvisor/utils/sysfs/sysfs.go
vendor/modules.txt

This commit bumps the version of cadvisor to fix invalid metrics for container_fs_* on kubelet.
Fixes #
```release-note
```
```docs
```

OCPBUGS-57070: UPSTREAM: <carry>: Bump cadvisor version to fix container_fs metrics
